### ISSUE TITLE
incompatibility with excavated variants (broken texture) neoforge 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [Benjamin-Norton/AllTheTrims#49] opened 2024-10-20 18:58 UTC
https://mclo.gs/auDkq9N
![image](https://github.com/user-attachments/assets/7e20ac42-460e-4f1d-9b43-e3a5378e7cf1)

**Comment by VaporeonScripts** [comment] 2024-10-20 18:58
removing allthetrims fixed the issue, altough id like it to get fixed xD

**Comment by Bawnorton** [comment] 2024-10-20 20:46
Took a bit, but found the cause. RT's block atlas parsing overwrote the custom entries in DynamicAssetGenerator's block atlas, thus, preventing the atlas from loading properly and the textures to never generate. Fixed in RT 1.0.4

**Closed as completed by Bawnorton** 2024-10-20 20:46 UTC
