### ISSUE TITLE
Issue with Biome Makeover Paletted Permutation Textures

### ISSUE THREAD

**Issue by Lemonszz** [Benjamin-Norton/AllTheTrims#6] opened 2023-07-13 02:39 UTC
Hi - 
[A user reported this issue to me ](https://github.com/Lemonszz/Biome-Makeover/issues/227#issuecomment-1629822567)

I was able to track it down to only occurring when All The Trims was installed (+ dependencies).

I'm not sure what's causing it, the missing textures use the new "Paletted Permutation" system. The logs imply to me that the texture isn't getting added to the `blocks.png` atlas correctly. [Relevant file here ](https://github.com/Lemonszz/Biome-Makeover/blob/1.20/common/src/main/resources/assets/minecraft/atlases/blocks.json).

I'm not sure if you're doing anything that may prevent this from loading, or there is a mistake on my end.

I tested with All the Trims V2.1.3, 3.0.1 & 3.0.2, all had the same issue.

[My log with only relevant mods](https://gist.github.com/Lemonszz/1ffea4fca7d5301447733639a4cebb1d). A user log can be found on the initial report. 

Do let me know if you think it might be on my end.
Thanks!

**Comment by Bawnorton** [comment] 2023-07-13 02:49
Hi, yes this does look like it may be caused by all the trims. I'm currently away but will be able to look more closely into this tomorrow afternoon.

**Comment by Bawnorton** [comment] 2023-07-13 22:42
Found the cause of the issue, and patched it in the next release. I'll close this when I release the update.

<img width="621" alt="Screenshot 2023-07-13 at 6 42 03 PM" src="https://github.com/Benjamin-Norton/AllTheTrims/assets/18416784/9bc78a59-18f6-46e9-9b81-a6c571dff451">

**Comment by Bawnorton** [comment] 2023-07-15 01:39
Fixed in [3.1.0](https://github.com/Benjamin-Norton/AllTheTrims/releases/tag/3.1.0)

**Closed as completed by Bawnorton** 2023-07-15 01:39 UTC
Labels: bug
