### ISSUE TITLE
[Bug Report] Regular Trim material don't render on item

### ISSUE THREAD

**Issue by Dowar** [Benjamin-Norton/AllTheTrims#17] opened 2023-10-19 01:01 UTC
**Expected Behaviour**
Trim render on item show correcly with regular material and don't mess up render of item when non-vanilla material don't

**Actual Behaviour**
With Dynamic Trim, when using regular material (iron, gold, amethyst etc...) on armors , the item does not show the trim (but the model when equipped does), also Silent Gear no longer even displays the color of the armor alloy and becomes gray, but works perfectly as soon as you add non-vanilla materials)

**Steps to Reproduce**
- Install Dynamic Trim
- Install Silent Gear
- Try to trim an armor with regular material (like gold), an another with non-vanilla material (like golden apple) to see the difference
- Put an armor in crafting table (like golden armor) to convert to Silent Gear armor
- try to trim Silent Gear armor with regular material, and with non-vanilla material to see the difference

**Idea to fix**
Add an option to dynamically render color palette of regular item too instead of the vanilla behavior

**What version of the mod are you using**
- Minecraft 1.20.1
- All The Trims 2.1.0
- Dynamic Trim 1.2.1
- Silent Gear 3.5.1

**Comment by Bawnorton** [comment] 2023-10-19 22:03
Confirmed this is happening, I'll look into a fix. The root cause appears to be in Dynamic Trim.

**Comment by Bawnorton** [comment] 2023-10-21 17:30
Fixed in Dynamic Trims 1.3.0

**Closed as completed by Bawnorton** 2023-10-21 17:30 UTC
Labels: bug
