### ISSUE TITLE
[Bug Report] game crashes for no apparent reason

### ISSUE THREAD

**Issue by sayao** [Benjamin-Norton/AllTheTrims#3] opened 2023-06-26 18:02 UTC
**Expected Behaviour**
the game should work normally

**Actual Behaviour**
game crashes as soon as i make a new world/enter an old world

**Steps to Reproduce**
just use the mod, it's that simple

**What version of the mod are you using**
allthetrims-2.1.1.

**Helpful Files**
[crash-2023-06-23_21.33.33-client.txt](https://github.com/Benjamin-Norton/AllTheTrims/files/11872289/crash-2023-06-23_21.33.33-client.txt)

- latest.log
  - Found in `.minecraft/logs`

**Comment by Bawnorton** [comment] 2023-06-26 18:06
You're using 1.3.0, also the crash log does not appear to contain the whole error. Please can you send your `latest.log` as that will contain the cause of the crash.

**Comment by sayao** [comment] 2023-06-26 18:12
[latest.log](https://github.com/Benjamin-Norton/AllTheTrims/files/11872378/latest.log)
perhaps this is what your looking for, I hope chocolatemystery stops bugging me about this

**Comment by Bawnorton** [comment] 2023-06-26 18:18
Well that crash is very odd, I can't reproduce it but I'll see if I can fix it anyway.

**Comment by Bawnorton** [comment] 2023-06-26 18:32
Should be fixed in 2.1.2

**Closed as completed by Bawnorton** 2023-06-26 18:32 UTC
Labels: bug
